### PR TITLE
Allow accessing un-wrapped worker instance

### LINKED ISSUE #111: Access to un-wrapped worker instance
According to https://github.com/GoogleChromeLabs/comlink/issues/372, in order to terminate a worker before it has completed, we need to call `worker.terminate()` on the worker instance. Calling it on the proxy won't work.

This package generates code like:
```js
const proxy = wrap(
            new Worker(
              new URL("/src/components/print/print-react/internal:comlink:./documents/campPrint/my-custom.worker.js?type=module&worker_file", self.location)
              , {type: "module"})
          )
```
This way, accessing the `new Worker(...)` part is not possible. I had a look at the Comlink code, and there does not seem to be an easy way to "unwrap" the proxy.

Do you see any easy way for this package to provide access to the worker instance instead of the proxy? Or at least a way to access the `terminate` method on the worker instance?

### PR DESCRIPTION
**Pull request by carlobeltrame**
Fixes #111, by allowing the following:
```js
const proxy = new ComlinkWorker(new URL('./my.worker.js', import.meta.url))
proxy[Symbol.for('endpoint')].terminate()
```
Which gets transformed into the following code (whitespace adjusted for readability):
```js
const proxy = ((function() {
  const endpoint = new ComlinkWorker(
    new URL('internal:comlink:./my.worker.js', import.meta.url)
  );
  const wrapped = wrap(endpoint);
  return new Proxy(wrapped, {
    get(target, prop, receiver) {
      if (prop === Symbol.for('endpoint')) return endpoint;
      return Reflect.get(...arguments);
    }
  });
})())
proxy[Symbol.for('endpoint')].terminate()
```

I named the property `endpoint` to take into account that in the case of shared workers, it's not a worker but a port instead, and Comlink calls this Worker|MessagePort hybrid type "endpoint".

### CODE REVIEW

**Comment by mathe42** [comment]
Thanks for the PR.

I have some issues with the change
1. The name endpoint is bad. We should use a symbol instead maybe with Symbol.for.
2. As wrap(endpoint) is a Proxy wrapped.endpoint = endpoint; will not work as expected to properly implement this we would need to wrap  wrap(endpoint) in a new Proxy. (Problem 1: I'm not convinced that this code works; Problem 2: A non breaking change in comlink could break this)

**Comment by carlobeltrame** [comment]
Thanks for the quick reply! I implemented the changes you requested: It now uses `Symbol.for('endpoint')` for accessing the endpoint, and it now wraps the Comlink Proxy in another proxy to make sure the access to the endpoint isn't intercepted by the Comlink Proxy.
I also did a rudimentary local test of this version, by building the package and copying it into a Vite project where I logged the Worker instance and used the terminate() function on it. It worked on my machine. Let me know if I can provide any proof or unit test or reproduction of it working.

However, I don't necessarily need this code to be the final solution. This PR is just a proposal to get the ball rolling. If you have any other ideas how to solve this, I'm all for it.

**Comment by mathe42** [comment]
That looks good. I will test it and release it.

**Comment by mathe42** [comment]
Had to change the implementation so we get full TS support.

**Pull request merged**
